"""Adiciona campos de status ao slave modbus

Revision ID: 6865a4dca88e
Revises: 9f970caecef5
Create Date: 2025-10-20 19:40:43.175979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6865a4dca88e'
down_revision = '9f970caecef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modbus_slave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='Indefinido', nullable=False))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modbus_slave', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
