"""empty message

Revision ID: 9cf6d14a5934
Revises: 
Create Date: 2025-10-14 19:59:39.320805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf6d14a5934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcao_registrador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcao')
    )
    op.create_table('grupo_bombeamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('modbus_slave',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('slave_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slave_id')
    )
    op.create_table('situacao',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_de_reservatorio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tubos',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('pol', sa.String(length=10), nullable=False),
    sa.Column('mm', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('privilegio', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('enviar_email', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('modbus_register',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slave_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=True),
    sa.Column('funcao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcao_registrador.id'], ),
    sa.ForeignKeyConstraint(['slave_id'], ['modbus_slave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservatorio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=80), nullable=False),
    sa.Column('capacidade_maxima', sa.Float(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('modbus_slave_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modbus_slave_id'], ['modbus_slave.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_de_reservatorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerta_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservatorio_id', sa.Integer(), nullable=False),
    sa.Column('limite_inferior', sa.Float(), nullable=False),
    sa.Column('limite_superior', sa.Float(), nullable=False),
    sa.Column('email_notificacao', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('timestamp_criacao', sa.DateTime(), nullable=False),
    sa.Column('timestamp_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservatorio_id'], ['reservatorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modbus_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['register_id'], ['modbus_register.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motobomba',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=30), nullable=False),
    sa.Column('fabricante', sa.String(length=30), nullable=False),
    sa.Column('potencia', sa.String(length=10), nullable=False),
    sa.Column('succao_id', sa.SmallInteger(), nullable=False),
    sa.Column('recalque_id', sa.SmallInteger(), nullable=False),
    sa.Column('tensao_de_trabalho', sa.Enum('V110', 'V220', 'V380', 'V440', name='tensaotrabalho'), nullable=False),
    sa.Column('modbus_slave_id', sa.Integer(), nullable=True),
    sa.Column('reservatorio_fonte_id', sa.Integer(), nullable=True),
    sa.Column('reservatorio_destino_id', sa.Integer(), nullable=True),
    sa.Column('grupo_bombeamento_id', sa.Integer(), nullable=True),
    sa.Column('funcao', sa.Enum('PRINCIPAL', 'RESERVA', name='funcaobomba'), nullable=False),
    sa.Column('status_rotacao', sa.Enum('ATIVA', 'EM_ESPERA', name='statusrotacao'), nullable=False),
    sa.Column('ultimo_acionamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_bombeamento_id'], ['grupo_bombeamento.id'], ),
    sa.ForeignKeyConstraint(['modbus_slave_id'], ['modbus_slave.id'], ),
    sa.ForeignKeyConstraint(['recalque_id'], ['tubos.id'], ),
    sa.ForeignKeyConstraint(['reservatorio_destino_id'], ['reservatorio.id'], ),
    sa.ForeignKeyConstraint(['reservatorio_fonte_id'], ['reservatorio.id'], ),
    sa.ForeignKeyConstraint(['succao_id'], ['tubos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('nivel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('reservatorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservatorio_id'], ['reservatorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acionamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_lig', sa.Time(), nullable=False),
    sa.Column('hora_des', sa.Time(), nullable=True),
    sa.Column('tensao', sa.Float(), nullable=True),
    sa.Column('corrente', sa.Float(), nullable=True),
    sa.Column('potencia', sa.Float(), nullable=True),
    sa.Column('consumo', sa.Float(), nullable=True),
    sa.Column('consumo_kwh', sa.Float(), nullable=True),
    sa.Column('mb_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('situacao_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['mb_id'], ['motobomba.id'], ),
    sa.ForeignKeyConstraint(['situacao_id'], ['situacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motobomba_alerta_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motobomba_id', sa.Integer(), nullable=False),
    sa.Column('perc_variacao_tensao', sa.Float(), nullable=False),
    sa.Column('perc_variacao_corrente', sa.Float(), nullable=False),
    sa.Column('email_notificacao', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('timestamp_criacao', sa.DateTime(), nullable=False),
    sa.Column('timestamp_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['motobomba_id'], ['motobomba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motobomba_alerta_config')
    op.drop_table('acionamento')
    op.drop_table('nivel')
    op.drop_table('motobomba')
    op.drop_table('modbus_data')
    op.drop_table('alerta_config')
    op.drop_table('reservatorio')
    op.drop_table('modbus_register')
    op.drop_table('usuario')
    op.drop_table('tubos')
    op.drop_table('tipo_de_reservatorio')
    op.drop_table('situacao')
    op.drop_table('modbus_slave')
    op.drop_table('grupo_bombeamento')
    op.drop_table('funcao_registrador')
    # ### end Alembic commands ###
