"""empty message

Revision ID: 9f970caecef5
Revises: dcfb143992bc
Create Date: 2025-10-18 16:43:47.175263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f970caecef5'
down_revision = 'dcfb143992bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modbus_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=20), server_default='int16', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modbus_register', schema=None) as batch_op:
        batch_op.drop_column('data_type')

    # ### end Alembic commands ###
