"""empty message

Revision ID: dcfb143992bc
Revises: 9cf6d14a5934
Create Date: 2025-10-14 20:16:57.170080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfb143992bc'
down_revision = '9cf6d14a5934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modbus_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acesso', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tamanho', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modbus_register', schema=None) as batch_op:
        batch_op.drop_column('tamanho')
        batch_op.drop_column('acesso')

    # ### end Alembic commands ###
